var sprites = {
	"empty": "       <br>       <br>       ",
	"basic": "|`````|<br>|     |<br>|_____|",
	"gold-one": "|`````|<br>|  0  |<br>|_____|",
	"gold-three": "|`````|<br>|  0  |<br>|0___0|",
	"gold-five": "|0```0|<br>|  0  |<br>|0___0|",
	"hard-one": "|: : :|<br>: : : :<br>|: : :|",
	"hard-one-gold-three": "|0 : 0|<br>|: 0 :|<br>|: : :|",
	"hard-ten": "{|||||}<br>{|||||}<br>{|||||}",
	"stick-basic": "   O   <br>  /|\\  <br>  / \\  ",
	"stick-dig-right": "__O    <br>\\-|\\--><br> / \\   ",
	"stick-dig-left": "    O__<br><--/|-/<br>   / \\ ",
	"stick-dig-down": "   O/\\ <br>  /\\_| <br> /|  V ",
	"stick-dig-up": "   O A  <br>  |\\=| <br> / \\ | ",
};